// Generated by CoffeeScript 1.10.0
(function() {
  var MyD3, obj;

  MyD3 = (function() {
    function MyD3() {}

    MyD3.prototype.size = {
      width: 200,
      height: 100
    };

    MyD3.prototype.generateData = function() {
      var i, j, list, lots, maxValue, ref;
      lots = 10;
      maxValue = 30;
      list = [];
      for (i = j = 1, ref = lots; 1 <= ref ? j < ref : j > ref; i = 1 <= ref ? ++j : --j) {
        list.push(Math.round(Math.random() * maxValue));
      }
      return list;
    };

    MyD3.prototype.bowGraph = function(data) {
      var svg;
      return svg = $(".bowGraph").append("svg").attr({
        width: this.size.width,
        height: this.size.height
      });
    };

    MyD3.prototype.circleGraph = function(data) {
      var svg;
      return svg = $(".circleGraph").append("svg").attr({
        width: this.size.width,
        height: this.size.height
      });
    };

    MyD3.prototype.test = function() {
      return console.log(this.generateData());
    };

    return MyD3;

  })();

  obj = new MyD3();

  obj.bowGraph();

  obj.circleGraph();

}).call(this);
